---
- name: Setup Nginx Web Server 
  hosts: webservers
  become: yes
  vars:
    web_content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Welcome</title>
      </head>
      <body>
          <h1>Hello Ansible from Tyseer</h1>
      </body>
      </html>
  tasks:
  - name: Update apt cache
    ansible.builtin.apt:
         update_cache: yes
         
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.apt:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy HTML content
      ansible.builtin.apt:
        content: "{{ web_content }}"
        dest: /usr/share/nginx/html/index.html

    - name: Ensure Nginx is running
      ansible.builtin.apt:
        name: nginx
        state: started

